1.write a numpy program to create an array of 10 zeros ,10 ones ,10 fives

In [1]:
import numpy as np
a=np.zeros(10)
b=np.ones(10)
c=np.ones(10)*5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2.write a numpy program to create an array of the integer from 30-70

In [8]:
t=np.arange(30,71)
t

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

3.write a numpy program to create an array of all the even integer from 30-70

In [13]:
e=np.arange(30,70,2)#(start,end,step)
e

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

4.write a numpy program to create an 3x3 identity matrix

In [20]:
m=np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5.write a numpy program to generate a random number between 0 and 1

In [23]:
n=np.random.normal(0,1,1)
n

array([-0.65637663])

In [27]:
n1=np.arange(0,1)
n1

array([0])

6.write a numpy program to compute sum of all elements ,sum of each columns and each row of a given array

In [29]:
x=np.array([[11,22],[22,4]])
print(x,np.sum(x),np.sum(x,axis=0),np.sum(x,axis=1))

[[11 22]
 [22  4]] 59 [33 26] [33 26]


7.how to replace items that satisfy a condition with another value in numpy array
input--->arr=np.array([0,1,2,3,4,5,6,7,8,9])
      output-->array([0,-1,2,-1,4,-1,6,-1,8,-1])

In [30]:
x1=np.array([0,1,2,3,4,5,6,7,8,9])


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
8.convert a 1D array to a 2D array with 2 rows with np.arange(10)
input-->array([0,1,2,3,4,5,6,7,8,9])
output->array([[0,1,2,3,4],[5,6,7,8,9]])

In [ ]:
9.get the common items between a and b 
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
output-->array([2,4])

10.get all items between 5 and 10 from a 
a=np.array([2,6,1,9,10,3,27])
output-->(array([6,9,10]),)