In [1]:
#element

In [2]:
import pandas as pd
df=pd.DataFrame({"name":['pinky','pop','push','pups'],
                 "rollnumbers":[401,402,403,30],
                 "branch":['cse','ece','civil','mech']},index=[1,2,3,4])
df

name  rollnumbers branch
1  pinky          401    cse
2    pop          402    ece
3   push          403  civil
4   pups           30   mech

In [4]:
df.loc[1]

name           pinky
rollnumbers      401
branch           cse
Name: 1, dtype: object

In [6]:
df.loc[2]['rollnumbers']

402

In [7]:
df.iloc[3]

name           pups
rollnumbers      30
branch         mech
Name: 4, dtype: object

In [8]:
df.iloc[2]['branch']

'civil'

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 1 to 4
Data columns (total 3 columns):
name           4 non-null object
rollnumbers    4 non-null int64
branch         4 non-null object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes


In [9]:
df.describe()

rollnumbers
count     4.000000
mean    309.000000
std     186.001792
min      30.000000
25%     308.250000
50%     401.500000
75%     402.250000
max     403.000000

In [10]:
df.count()

name           4
rollnumbers    4
branch         4
dtype: int64

In [11]:
df.dtypes

name           object
rollnumbers     int64
branch         object
dtype: object

In [12]:
df.count(axis='rows') # columns output

name           4
rollnumbers    4
branch         4
dtype: int64

In [13]:
df.count(axis=1) # rows

1    3
2    3
3    3
4    3
dtype: int64

In [14]:
df.count(axis=0)

name           4
rollnumbers    4
branch         4
dtype: int64

In [15]:
df.count(axis='columns') #rows output

1    3
2    3
3    3
4    3
dtype: int64

In [16]:
df

name  rollnumbers branch
1  pinky          401    cse
2    pop          402    ece
3   push          403  civil
4   pups           30   mech

In [17]:
df.set_index(["rollnumbers"])

name branch
rollnumbers              
401          pinky    cse
402            pop    ece
403           push  civil
30            pups   mech

In [18]:
df.set_index(["rollnumbers","name"])

branch
rollnumbers name        
401         pinky    cse
402         pop      ece
403         push   civil
30          pups    mech

In [20]:
import numpy as np
f1=pd.Series([9,12,3,4,5])
f1

0     9
1    12
2     3
3     4
4     5
dtype: int64

In [21]:
f1.isnull()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [22]:
f1.describe()

count     5.000000
mean      6.600000
std       3.781534
min       3.000000
25%       4.000000
50%       5.000000
75%       9.000000
max      12.000000
dtype: float64

In [23]:
f1.count()

5

In [28]:
np.arange(3,9)


array([3, 4, 5, 6, 7, 8])

In [31]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
data=pd.DataFrame(np.arange(12))
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [34]:
data=pd.DataFrame(np.arange(12).reshape(4,3))# default index starts from zeros
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [35]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [38]:
d1=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))
d1

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [40]:
d1.loc[1]['c']

7

In [42]:
#replace the non value to the particular element
d1.loc[1,'c']=np.nan
d1

a   b     c   d   e
0   0   1   2.0   3   4
1   5   6   NaN   8   9
2  10  11  12.0  13  14
3  15  16  17.0  18  19

In [43]:
d1.isnull()

a      b      c      d      e
0  False  False  False  False  False
1  False  False   True  False  False
2  False  False  False  False  False
3  False  False  False  False  False

In [44]:
d1.isnull().sum()

a    0
b    0
c    1
d    0
e    0
dtype: int64

In [45]:
df

name  rollnumbers branch
1  pinky          401    cse
2    pop          402    ece
3   push          403  civil
4   pups           30   mech

In [46]:
d1+df

a   b branch   c   d   e name  rollnumbers
0 NaN NaN    NaN NaN NaN NaN  NaN          NaN
1 NaN NaN    NaN NaN NaN NaN  NaN          NaN
2 NaN NaN    NaN NaN NaN NaN  NaN          NaN
3 NaN NaN    NaN NaN NaN NaN  NaN          NaN
4 NaN NaN    NaN NaN NaN NaN  NaN          NaN

In [48]:
dd=df.add(d1)
dd

a   b branch   c   d   e name  rollnumbers
0 NaN NaN    NaN NaN NaN NaN  NaN          NaN
1 NaN NaN    NaN NaN NaN NaN  NaN          NaN
2 NaN NaN    NaN NaN NaN NaN  NaN          NaN
3 NaN NaN    NaN NaN NaN NaN  NaN          NaN
4 NaN NaN    NaN NaN NaN NaN  NaN          NaN

In [53]:
dd.add(data,fill_value=1)

a     b branch     c   d   e name  rollnumbers
0   1.0   2.0    NaN   3.0 NaN NaN  NaN          NaN
1   4.0   5.0    NaN   6.0 NaN NaN  NaN          NaN
2   7.0   8.0    NaN   9.0 NaN NaN  NaN          NaN
3  10.0  11.0    NaN  12.0 NaN NaN  NaN          NaN
4   NaN   NaN    NaN   NaN NaN NaN  NaN          NaN

In [54]:
dd.add(data,fill_value=0) #it will replace in zero values

a     b branch     c   d   e name  rollnumbers
0  0.0   1.0    NaN   2.0 NaN NaN  NaN          NaN
1  3.0   4.0    NaN   5.0 NaN NaN  NaN          NaN
2  6.0   7.0    NaN   8.0 NaN NaN  NaN          NaN
3  9.0  10.0    NaN  11.0 NaN NaN  NaN          NaN
4  NaN   NaN    NaN   NaN NaN NaN  NaN          NaN

In [55]:
dd.add(data,fill_value=9)

a     b branch     c   d   e name  rollnumbers
0   9.0  10.0    NaN  11.0 NaN NaN  NaN          NaN
1  12.0  13.0    NaN  14.0 NaN NaN  NaN          NaN
2  15.0  16.0    NaN  17.0 NaN NaN  NaN          NaN
3  18.0  19.0    NaN  20.0 NaN NaN  NaN          NaN
4   NaN   NaN    NaN   NaN NaN NaN  NaN          NaN

In [56]:
np.random.randn(2,4) #random values in numpy array-------->randn

array([[ 0.56729355, -2.28492982,  0.11956316, -1.05830226],
       [ 0.18021117,  1.01332702, -0.12070238, -1.5459422 ]])

In [57]:
np.random.rand(2,4) #random values in numpy array----->rand

array([[0.83714448, 0.07594939, 0.56557378, 0.62230418],
       [0.84852206, 0.59671022, 0.46781997, 0.78052907]])

In [60]:
np.random.rand(2,8)

array([[0.58040911, 0.47711964, 0.3948523 , 0.89791907, 0.32126511,
        0.95246497, 0.76378109, 0.44306098],
       [0.92151142, 0.07789934, 0.96126601, 0.84171249, 0.53786822,
        0.6846086 , 0.52792055, 0.96258009]])

In [63]:
# creating dataframe with random values
r=pd.DataFrame(np.random.rand(3,4))
r

0         1         2         3
0  0.356720  0.721375  0.695000  0.326338
1  0.770570  0.037776  0.076342  0.859552
2  0.365163  0.769258  0.120928  0.377608

In [65]:
r=pd.DataFrame(np.random.rand(3,4),index=['a','b','c'],columns=['s1','s2','s3','s4'])
r

s1        s2        s3        s4
a  0.708654  0.988459  0.974708  0.532821
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413

In [72]:
r.index=['a','b','c']
r

s1        s2        s3        s4
a  0.708654  0.988459  0.974708  0.532821
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413

In [73]:
r.columns=['s1','s2','s3','s4']
r

s1        s2        s3        s4
a  0.708654  0.988459  0.974708  0.532821
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413

In [75]:
#reindexing
r1=r.reindex(['b','c','d','a'])
r1

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN
a  0.708654  0.988459  0.974708  0.532821

In [76]:
r1.isnull().sum() #finding null and sum values

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [79]:
n1=r1.isnull()
n1

s1     s2     s3     s4
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
a  False  False  False  False

In [80]:
n1.sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [81]:
r1.dropna() #dropping the null values

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
a  0.708654  0.988459  0.974708  0.532821

In [83]:
r1.fillna(4)# filling null values with 4

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d  4.000000  4.000000  4.000000  4.000000
a  0.708654  0.988459  0.974708  0.532821

In [85]:
r1.fillna(method='bfill',axis=1).fillna(1)#backward filling

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d  1.000000  1.000000  1.000000  1.000000
a  0.708654  0.988459  0.974708  0.532821

In [89]:
r1.fillna(method='ffill',axis=0).fillna(1) #forward filling

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d  0.132139  0.108605  0.258911  0.589413
a  0.708654  0.988459  0.974708  0.532821

In [90]:
r1.isna() #none--------true

s1     s2     s3     s4
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
a  False  False  False  False

In [91]:
r1.isnull()#np.NaN--------TRUE

s1     s2     s3     s4
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
a  False  False  False  False

In [93]:
pd.isna(r1['s1'])# it will allow only columns

b    False
c    False
d     True
a    False
Name: s1, dtype: bool

In [94]:
pd.isna(r1['s4'])

b    False
c    False
d     True
a    False
Name: s4, dtype: bool

In [95]:
#data replacing
r1

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN
a  0.708654  0.988459  0.974708  0.532821

In [96]:
aaa=pd.DataFrame({11:[3,4,5],12:[6,7,8],13:[2,3,4]})
aaa

11  12  13
0   3   6   2
1   4   7   3
2   5   8   4

In [98]:
aaa.replace(4,999)

11  12   13
0    3   6    2
1  999   7    3
2    5   8  999

In [99]:
aaa.replace([6,3,5],(111,222,333))

11   12   13
0  222  111    2
1    4    7  222
2  333    8    4

In [100]:
#index sorting and ranking
r1 # r1 is in un ordered data          reindexcommand  --------r1.reindex(['a','c','d','b'])

s1        s2        s3        s4
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN
a  0.708654  0.988459  0.974708  0.532821

In [101]:
r1.sort_index()

s1        s2        s3        s4
a  0.708654  0.988459  0.974708  0.532821
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN

In [103]:
r1.columns=['s4','s1','s3','s2']
r1

s4        s1        s3        s2
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN
a  0.708654  0.988459  0.974708  0.532821

In [104]:
r1.sort_index(axis=0)  #---->sorting columns

s4        s1        s3        s2
a  0.708654  0.988459  0.974708  0.532821
b  0.040358  0.270820  0.639578  0.465720
c  0.132139  0.108605  0.258911  0.589413
d       NaN       NaN       NaN       NaN

In [105]:
r1.sort_index(axis=1)   #---->sorting rows

s1        s2        s3        s4
b  0.270820  0.465720  0.639578  0.040358
c  0.108605  0.589413  0.258911  0.132139
d       NaN       NaN       NaN       NaN
a  0.988459  0.532821  0.974708  0.708654

In [114]:
#groupby
animal_df=pd.DataFrame({'name':['cat','dog','cow','dog','cat'],
                        'place':['heart','zoo','home','zoo','heart'],
                       'feature':['colour','height','a','height1','colour1']})
animal_df

name  place  feature
0  cat  heart   colour
1  dog    zoo   height
2  cow   home        a
3  dog    zoo  height1
4  cat  heart  colour1

In [115]:
animal_df.groupby('name').sum()

place        feature
name                           
cat   heartheart  colourcolour1
cow         home              a
dog       zoozoo  heightheight1

In [116]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [117]:
animal_df.groupby(['name','feature']).sum()

place
name feature       
cat  colour   heart
     colour1  heart
cow  a         home
dog  height     zoo
     height1    zoo

In [118]:
animal_df.groupby(['feature']).sum()

name  place
feature            
a        cow   home
colour   cat  heart
colour1  cat  heart
height   dog    zoo
height1  dog    zoo

In [136]:
animal_df1=pd.DataFrame({'name':['cat','dog','cow','dog','cat'],
                        'place':['heart','zoo','home','zoo','heart'],
                        'legs':[3,4,2,4,np.nan]})
animal_df1

name  place  legs
0  cat  heart   3.0
1  dog    zoo   4.0
2  cow   home   2.0
3  dog    zoo   4.0
4  cat  heart   NaN

In [137]:
animal_df1["rank1"]=animal_df1['legs'].rank()
animal_df1

name  place  legs  rank1
0  cat  heart   3.0    2.0
1  dog    zoo   4.0    3.5
2  cow   home   2.0    1.0
3  dog    zoo   4.0    3.5
4  cat  heart   NaN    NaN

In [138]:
animal_df1["max_rank"]=animal_df1['legs'].rank(method="max")
animal_df1

name  place  legs  rank1  max_rank
0  cat  heart   3.0    2.0       2.0
1  dog    zoo   4.0    3.5       4.0
2  cow   home   2.0    1.0       1.0
3  dog    zoo   4.0    3.5       4.0
4  cat  heart   NaN    NaN       NaN

In [139]:
animal_df1["first_rank"]=animal_df1['legs'].rank(method="first")
animal_df1

name  place  legs  rank1  max_rank  first_rank
0  cat  heart   3.0    2.0       2.0         2.0
1  dog    zoo   4.0    3.5       4.0         3.0
2  cow   home   2.0    1.0       1.0         1.0
3  dog    zoo   4.0    3.5       4.0         4.0
4  cat  heart   NaN    NaN       NaN         NaN

In [124]:
animal_df1["non_rank"]=animal_df1['legs'].rank(na_option="bottom")
animal_df1

name  place legs  rank1  max_rank  non_rank
0  cat  heart    3    2.0       2.0       2.0
1  dog    zoo    4    3.5       4.0       3.5
2  cow   home    2    1.0       1.0       1.0
3  dog    zoo    4    3.5       4.0       3.5
4  cat  heart  NaN    NaN       NaN       5.0

In [127]:
animal_df1["pct_rank"]=animal_df1['legs'].rank(pct=True)
animal_df1

name  place legs  rank1  max_rank  non_rank  pct_rank
0  cat  heart    3    2.0       2.0       2.0     0.500
1  dog    zoo    4    3.5       4.0       3.5     0.875
2  cow   home    2    1.0       1.0       1.0     0.250
3  dog    zoo    4    3.5       4.0       3.5     0.875
4  cat  heart  NaN    NaN       NaN       5.0       NaN

# categorise

In [145]:
cate=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,11]})
cate

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  11

In [146]:
cate["cc"]=cate['y'].astype('category')
cate

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  11  11

In [147]:
cate["cc"]

0     6
1     7
2     8
3     9
4    11
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 11]

In [148]:
cate["cc"].cat.categories=["good","excellent","brillient","intelligent","super"]
cate

x   y           cc
0  1   6         good
1  2   7    excellent
2  3   8    brillient
3  4   9  intelligent
4  5  11        super

In [150]:
cate["cc"]=cate['cc'].set_categories=["good","excellent","brillient","intelligent","super"]
cate

x   y           cc
0  1   6         good
1  2   7    excellent
2  3   8    brillient
3  4   9  intelligent
4  5  11        super

In [151]:
cate.sort_values('cc')

x   y           cc
2  3   8    brillient
1  2   7    excellent
0  1   6         good
3  4   9  intelligent
4  5  11        super

In [152]:
cate.groupby("cc").sum()

x   y
cc                
brillient    3   8
excellent    2   7
good         1   6
intelligent  4   9
super        5  11

In [153]:
cate.groupby("cc").size()

cc
brillient      1
excellent      1
good           1
intelligent    1
super          1
dtype: int64

# reading the data 

In [155]:
df=pd.read_table("text1.txt")
df

C:\Users\kvsw12\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


hanumantha reddygaru
0           10000001211
1              10000332
2            1237372788

In [157]:
df=pd.read_table("ex1.csv")
df

C:\Users\kvsw12\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [159]:
df=pd.read_table("ex1.csv",sep=",")
df

C:\Users\kvsw12\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [161]:
df=pd.read_csv("ex1.csv")
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [163]:
df=pd.read_csv("ex2.csv")
df

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo